### ISSUE TITLE
Show "Abo-Typ" in "Abo"-overview

### ISSUE THREAD

**Issue by LouRB** [Rote-Beete/organisatorisches#1]
Our Abos have a kind of ID, which is built from a letter and two numbers, for example J13. The Abos have different prices and sizes, so we would want to use "Abo-Typ" as the ID oder Name for the individual "Abo". To work with Juntagrico it would be necessary to see the "Abo-Typ" in the "Abo"-Overview. Only in the list-exports wouldn't be enough.

Hab das auch hier angelegt, soll ich das rausnehmen?
https://github.com/juntagrico/juntagrico/issues/371

**Comment by georgkrause** [comment]
Lets break this down: You want to have some additional information. Where should this be shown? Not sure whats "Abo-Overview" (You can simply copy me the URL from your browser when you are at the page). 

As far as I can see one Subscription can have multiple sized products, so it might be a problem to pick the right one

**Comment by LouRB** [comment]
Should be shown here: http://localhost/admin/juntagrico/subscription/

**Comment by LouRB** [comment]
Here it would be helpful http://localhost/admin/juntagrico/subscription/

**Comment by LouRB** [comment]
and here http://localhost/my/subscriptions might be more important

**Comment by georgkrause** [comment]
Thanks for the clarification :)

So the problem is the listed data can be connected to several `types`, so we need to be able to pick the right one or simply show all. I am going to do some tests and keep you updated.

To get this upstream where you created the issue it might be the best to implement a "column picker" where you can choose which columns to show in this table. But I will move this discussion there.

**Comment by LouRB** [comment]
https://github.com/juntagrico/juntagrico/issues/371
